/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AssistantIndexRouteImport } from './routes/assistant/index'
import { Route as SeriesImdbIDRouteImport } from './routes/series/$imdbID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesImdbIDRoute = SeriesImdbIDRouteImport.update({
  id: '/series/$imdbID',
  path: '/series/$imdbID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/series/$imdbID': typeof SeriesImdbIDRoute
  '/assistant': typeof AssistantIndexRoute
  '/login': typeof LoginIndexRoute
  '/search': typeof SearchIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/series/$imdbID': typeof SeriesImdbIDRoute
  '/assistant': typeof AssistantIndexRoute
  '/login': typeof LoginIndexRoute
  '/search': typeof SearchIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/series/$imdbID': typeof SeriesImdbIDRoute
  '/assistant/': typeof AssistantIndexRoute
  '/login/': typeof LoginIndexRoute
  '/search/': typeof SearchIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/series/$imdbID'
    | '/assistant'
    | '/login'
    | '/search'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/series/$imdbID' | '/assistant' | '/login' | '/search' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/series/$imdbID'
    | '/assistant/'
    | '/login/'
    | '/search/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeriesImdbIDRoute: typeof SeriesImdbIDRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$imdbID': {
      id: '/series/$imdbID'
      path: '/series/$imdbID'
      fullPath: '/series/$imdbID'
      preLoaderRoute: typeof SeriesImdbIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeriesImdbIDRoute: SeriesImdbIDRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
